multinode: false

modelArtifacts:
  uri: "hf://openai/gpt-oss-120b"
  size: 250Gi
  authSecretName: "llm-d-hf-token"
  name: "openai/gpt-oss-120b"
  labels:
    llm-d.ai/inference-serving: "true"
    llm-d.ai/guide: "pd-disaggregation"
    llm-d.ai/hardware-vairant: "gpu"
    llm-d.ai/accelerator-vendor: "nvidia"
    llm-d.ai/model: "gpt-oss-120b"

routing:
  servicePort: 8000
  proxy:
    image: ghcr.io/llm-d/llm-d-routing-sidecar:v0.5.0
    connector: nixlv2
    secure: false

decode:
  parallelism:
    tensor: 4
  create: true
  replicas: 1
  monitoring:
    podmonitor:
      enabled: true
      portName: "vllm"  # decode vLLM service port (from routing.proxy.targetPort)
      path: "/metrics"
      interval: "30s"
  containers:
    - name: "vllm"
      image: ghcr.io/llm-d/llm-d-cuda:v0.5.0
      modelCommand: vllmServe
      args:
        - "--block-size"
        - "128"
        - "--kv-transfer-config"
        - '{"kv_connector":"NixlConnector", "kv_role":"kv_both"}'
        - "--disable-uvicorn-access-log"
        - "--max-model-len"
        - "32000"
      env:
        - name: VLLM_NIXL_SIDE_CHANNEL_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: HF_HOME
          value: "/mnt/hf-cache"
        - name: VLLM_CACHE_DIR
          value: "/mnt/vllm-cache"
        - name: UCX_NET_DEVICES
          value: "mlx5_0:1,mlx5_1:1,mlx5_2:1,mlx5_3:1,mlx5_4:1,mlx5_5:1,mlx5_6:1,mlx5_7:1,mlx5_8:1,mlx5_9:1,mlx5_10:1,mlx5_11:1"
      ports:
        - containerPort: 8200
          name: vllm
          protocol: TCP
        - containerPort: 5600
          name: nixl
          protocol: TCP
      resources:
        limits:
          memory: 64Gi
          cpu: "16"
          # note: GPU resources get controlled by parallelism + accelerators above
          # rdma/ib: 1
        requests:
          memory: 64Gi
          cpu: "16"
          # note: GPU resources get controlled by parallelism + accelerators above
          # rdma/ib: 1
      volumeMounts:
        - name: metrics-volume
          mountPath: /.config
        - name: shm
          mountPath: /dev/shm
        - name: vllm-cache
          mountPath: /mnt/vllm-cache
        - name: hf-cache
          mountPath: /mnt/hf-cache
      startupProbe:
        httpGet:
          path: /v1/models
          port: vllm
        initialDelaySeconds: 15
        periodSeconds: 30
        timeoutSeconds: 5
        failureThreshold: 60
      livenessProbe:
        httpGet:
          path: /health
          port: vllm
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /v1/models
          port: vllm
        periodSeconds: 5
        timeoutSeconds: 2
        failureThreshold: 3
  volumes:
    - name: metrics-volume
      emptyDir: {}
    - name: shm
      emptyDir:
        medium: Memory
        sizeLimit: "16Gi"
    - name: vllm-cache
      hostPath:
        path: /mnt/filesystem-x7/vllm-cache
        type: DirectoryOrCreate
    - name: hf-cache
      hostPath:
        path: /mnt/filesystem-x7/hf-cache
        type: DirectoryOrCreate

prefill:
  parallelism:
    tensor: 1
  create: true
  replicas: 4
  monitoring:
    podmonitor:
      enabled: true
      portName: "vllm"  # prefill vLLM service port (from routing.servicePort)
      path: "/metrics"
      interval: "30s"
  containers:
    - name: "vllm"
      image: ghcr.io/llm-d/llm-d-cuda:v0.5.0
      modelCommand: vllmServe
      args:
        - "--block-size"
        - "128"
        - "--kv-transfer-config"
        - '{"kv_connector":"NixlConnector", "kv_role":"kv_both"}'
        - "--disable-uvicorn-access-log"
        - "--max-model-len"
        - "32000"
      env:
        - name: VLLM_NIXL_SIDE_CHANNEL_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: HF_HOME
          value: "/mnt/hf-cache"
        - name: VLLM_CACHE_DIR
          value: "/mnt/vllm-cache"
        - name: UCX_NET_DEVICES
          value: "mlx5_0:1,mlx5_1:1,mlx5_2:1,mlx5_3:1,mlx5_4:1,mlx5_5:1,mlx5_6:1,mlx5_7:1,mlx5_8:1,mlx5_9:1,mlx5_10:1,mlx5_11:1"
      ports:
        - containerPort: 8000
          name: vllm
          protocol: TCP
        - containerPort: 5600
          name: nixl
          protocol: TCP
      resources:
        limits:
          memory: 64Gi
          cpu: "8"
          # note: GPU resources get controlled by parallelism + accelerators above
          # rdma/ib: 1
        requests:
          memory: 64Gi
          cpu: "8"
          # note: GPU resources get controlled by parallelism + accelerators above
          # rdma/ib: 1
      volumeMounts:
        - name: metrics-volume
          mountPath: /.config
        - name: shm
          mountPath: /dev/shm
        - name: vllm-cache
          mountPath: /mnt/vllm-cache
        - name: hf-cache
          mountPath: /mnt/hf-cache
      startupProbe:
        httpGet:
          path: /v1/models
          port: vllm
        initialDelaySeconds: 15
        periodSeconds: 30
        timeoutSeconds: 5
        failureThreshold: 60
      livenessProbe:
        httpGet:
          path: /health
          port: vllm
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /v1/models
          port: vllm
        periodSeconds: 5
        timeoutSeconds: 2
        failureThreshold: 3
  volumes:
    - name: metrics-volume
      emptyDir: {}
    - name: shm
      emptyDir:
        medium: Memory
        sizeLimit: "16Gi"
    - name: vllm-cache
      hostPath:
        path: /mnt/filesystem-x7/vllm-cache
        type: DirectoryOrCreate
    - name: hf-cache
      hostPath:
        path: /mnt/filesystem-x7/hf-cache
        type: DirectoryOrCreate
