apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: llm-d-model-server
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: llm-d-model-server
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args/0
        value: |-
          exec vllm serve \
            meta-llama/Llama-3.1-8B-Instruct \
            --port 8000 \
            --enable-lora \
            --max-loras 3 \
            --max-lora-rank 64 \
            --max-cpu-loras 5
  - target:
      kind: Deployment
      name: llm-d-model-server
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: VLLM_ALLOW_RUNTIME_LORA_UPDATING
          value: "True"
  - target:
      kind: Deployment
      name: llm-d-model-server
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          limits:
            nvidia.com/gpu: 1
          requests:
            nvidia.com/gpu: 1
