inferencePool:
  modelServers:
    matchLabels:
      llm-d.ai/inference-serving: "true"
      llm-d.ai/guide: "lora-serving"
inferenceExtension:
  monitoring:
    prometheus:
      enable: true
  pluginsConfigFile: "lora-serving.yaml"
  pluginsCustomConfig:
    lora-serving.yaml: |
      apiVersion: inference.networking.x-k8s.io/v1alpha1
      kind: EndpointPickerConfig
      plugins:
        - type: single-profile-handler
        - type: metrics-data-source
          parameters:
            scheme: http
            path: /metrics
            insecureSkipVerify: true
        - type: queue-scorer
        - type: kv-cache-utilization-scorer
        - type: prefix-cache-scorer
        - type: lora-affinity-scorer
        - type: max-score-picker
      schedulingProfiles:
        - name: default
          plugins:
            - pluginRef: queue-scorer
              weight: 1.0
            - pluginRef: kv-cache-utilization-scorer
              weight: 1.0
            - pluginRef: prefix-cache-scorer
              weight: 1.5
            - pluginRef: lora-affinity-scorer
              weight: 6.0
            - pluginRef: max-score-picker
