load:
  type: constant
  request_timeout: 10000
  stages:
  - rate: 30
    duration: 120
api: 
  type: completion
  streaming: true
server:
  type: vllm
  model_name: "deepseek-ai/DeepSeek-R1-0528"
  base_url: http://10.145.217.87:8000
  ignore_eos: true
tokenizer:
  pretrained_model_name_or_path: deepseek-ai/DeepSeek-R1-0528
data:
  type: random
  input_distribution:
    min: 2000          # min length of the synthetic prompts
    max: 2000          # max length of the synthetic prompts
    mean: 2000         # mean length of the synthetic prompts
    std_dev: 0           # standard deviation of the length of the synthetic prompts
  output_distribution:
    min: 2000            # min length of the output to be generated
    max: 2000            # max length of the output to be generated
    mean: 2000           # mean length of the output to be generated
    std_dev: 0           # standard deviation of the length of the output to be generated
report:
  request_lifecycle:
    summary: true
    per_stage: true
    per_request: true